version: '3.8'
name: 'bradery'
x-backend-env: &backend-env
  - DATABASE_URL=mysql://root:password@db:3306/eshop
  - JWT_SECRET_KEY=my-secret
  - JWT_ACCESSTOKEN_EXPIRES_IN=1h
  - JWT_REFRESHTOKEN_EXPIRES_IN=100days
  - PORT=4001
  - REACT_APP_STRIPE=pk_test_51Msp05AR4Jq62RgVeDDk367gPqpIevXBlYLUhFi4sILsxtba3iJ1NNeAk202Zl1bLWpUhjOIlO1iyFGTADidpVum00AI6p2vXv
  - STRIPE_SK=sk_test_51Msp05AR4Jq62RgVFc6z4jdk3d8A86bReXzrBrya74qPtptFQI4FGSX2164ybzBQpCToz1ZoWsETTbYecUGNzl2x00JhRpR9x9
  - ENDPOINT_SECRET=whsec_c3e7b292f887e95f26a23cde0f0ed223ac6c9b49de45783913861719441c18ca
  - FRONTEND_ORIGIN=http://localhost:3000

services:
  db:
    image: mysql/mysql-server:8.0.20
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=% 
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  backend-db-migrations:
    build:
      context: ./
    depends_on:
      - db
    command: sh migrate.production.sh
    environment: *backend-env
  backend:
    depends_on:
      - backend-db-migrations
      - stripe-webhook-listener
    build: 
      context: ./
    environment: *backend-env
    ports:
      - 4001:4001
  stripe-webhook-listener:
    image: stripe/stripe-cli
    command: listen --forward-to backend:4001/stripe/webhook
    environment:
      - STRIPE_SK="sk_test_51Msp05AR4Jq62RgVFc6z4jdk3d8A86bReXzrBrya74qPtptFQI4FGSX2164ybzBQpCToz1ZoWsETTbYecUGNzl2x00JhRpR9x9"


volumes:
  db:
    driver: local