version: '3.8'
name: 'bradery'

services:
  db:
    image: mysql/mysql-server:8.0.20
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  backend-db-migrations:
      env_file: .env
      build:
        context: ./
      depends_on:
      - db
      command: sh migrate.production.sh
  backend:
    env_file: .env
    depends_on:
      - backend-db-migrations
      - stripe-webhook-listener
    build:
      context: ./
    ports:
      - 4001:4001
  stripe-webhook-listener:
    env_file: .env
    image: stripe/stripe-cli
    command: listen --forward-to backend:4001/stripe/webhook

volumes:
  db:
    driver: local